### ISSUE TITLE
B

### ISSUE THREAD

**Issue by Centro187** [mzollin/qr-pirate#264]

**Comment by mzollin** [comment]
C

**Comment by Centro187** [comment]
I can't seem to get this to work

**Comment by mzollin** [comment]
Hi, I'm sorry but I generally don't provide any support for my hobby projects, and this is honestly just a quick hack.
I just checked, the google and baidu crawlers are unfortunately still broken, maybe I will look into fixing that some day, or you can try to submit a PR. Apart from that, it is working for me (with the bing crawler). Try to follow the instructions in the README, good luck.
