### ISSUE TITLE
Used your code for a google dork able mod

### ISSUE THREAD

**Issue by alphaaurigae** [mzollin/qr-pirate#9]
Thought the idea of the repo is nice, but to really max it out one maybe needs to query detailed specific searches - so i went through a few image crawlers and came up with https://github.com/wolfhong/pisces - which seemed to be a perfect match, it works with any search query . Ive linked your repo in the readme.

https://github.com/alphaaurigae/Bitcoin-QR-dork

**Comment by alphaaurigae** [comment]
https://pypi.python.org/pypi/icrawler is very limited concerning the details of the search.
for ex i had a hard time to figure date_max=None format , still didnt.

**Comment by mzollin** [comment]
Can you please elaborate / give an example of useful search queries that are impossible with icrawler?
FYI the date and other attributes are documented here: http://icrawler.readthedocs.io/en/latest/usage.html#built-in-crawlers

**Comment by alphaaurigae** [comment]
WEll, after reviewing the link - if i can apply google operators through the search there shouldnt we anything but the tags you get presented in the browser, maybe i miss something.

Anyways, its a more intuitive approach, just copy paste the browser link. Thats why i came up with it, i couldnt figure the time format for a time sensitive query.

**Comment by blackunixteam** [comment]
alphaaurigae, could you reopen your bitcoin-qrcode-dork repo pls
